from typing import TypedDict


class AgentState(TypedDict):
    """
    Represents the state of our autonomous coding agent.
    This state is passed between different nodes in the LangGraph.
    It holds the source of truth for the task, the generated code/files,
    and execution feedback (stdout, stderr, exit codes, and review logs).
    """

    # The high-level task/problem description provided by the user.
    task: str

    # A list of sequential engineering steps generated by the Planner node.
    plan: list[str]

    # The index of the current step in the plan being processed (0-indexed).
    current_step_index: int

    # The primary Python code block generated by the Coder.
    code: str

    # A dictionary mapping file paths (relative to the workspace) to their contents.
    # This allows the agent to manage multiple files in the workspace.
    files: dict[str, str]

    # The script filename or CLI command to execute inside the sandbox
    # (e.g., "main.py" or "pytest").
    entry_point: str

    # The standard output (stdout) captured from the execution sandbox.
    stdout: str

    # The standard error (stderr) or traceback logs captured from the execution sandbox.
    stderr: str

    # The exit code returned by the sandboxed execution environment (0 means success).
    exit_code: int

    # Comments, warnings, or errors generated by the Reviewer node (Ruff / Bandit).
    review_comments: str

    # The current count of debugging/correction loops performed.
    retry_count: int

    # The maximum number of self-correction loops allowed before exiting.
    max_retries: int
